import type { Config } from 'tailwindcss';

const config: Config = {
    content: [
        './pages/**/*.{js,ts,jsx,tsx,mdx}',
        './components/**/*.{js,ts,jsx,tsx,mdx}',
        './app/**/*.{js,ts,jsx,tsx,mdx}',
    ],
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                'outline-variant': '#c1c6d7',
                'primary-fixed-dim': '#adc7ff',
                tertiary: '#9e3d00',
                'secondary-container': '#a4c1ff',
                secondary: '#405e96',
                'inverse-surface': '#213243',
                'primary-container': '#0070ea',
                'surface-container-low': '#eef4ff',
                'on-surface': '#0b1d2d',
                'tertiary-container': '#c64f00',
                'on-tertiary-fixed': '#351000',
                'surface-dim': '#cadcf2',
                primary: '#0059bb',
                'on-tertiary': '#ffffff',
                'on-tertiary-container': '#fffbff',
                'surface-variant': '#d2e4fb',
                outline: '#717786',
                'on-primary-fixed': '#001a41',
                'surface-container-high': '#d9eaff',
                'tertiary-fixed': '#ffdbcc',
                'surface-container-highest': '#d2e4fb',
                error: '#ba1a1a',
                'inverse-primary': '#adc7ff',
                'on-surface-variant': '#414754',
                'inverse-on-surface': '#e9f1ff',
                'error-container': '#ffdad6',
                'on-background': '#0b1d2d',
                'on-secondary': '#ffffff',
                background: '#f7f9ff',
                'on-primary': '#ffffff',
                surface: '#f7f9ff',
                'on-error': '#ffffff',
                'secondary-fixed-dim': '#adc7ff',
                'surface-bright': '#f7f9ff',
                'secondary-fixed': '#d8e2ff',
                'surface-container': '#e4efff',
                'on-primary-fixed-variant': '#004493',
                'on-secondary-container': '#2f4e85',
                'surface-tint': '#005bc0',
                'on-secondary-fixed': '#001a41',
                'primary-fixed': '#d8e2ff',
                'on-tertiary-fixed-variant': '#7c2e00',
                'on-primary-container': '#fefcff',
                'on-error-container': '#93000a',
                'tertiary-fixed-dim': '#ffb695',
                'surface-container-lowest': '#ffffff',
                'on-secondary-fixed-variant': '#26467c',
            },
            borderRadius: {
                DEFAULT: '0.125rem',
                lg: '0.375rem',
                xl: '0.5rem',
                full: '9999px',
            },
            fontFamily: {
                headline: ['Inter', 'sans-serif'],
                body: ['Inter', 'sans-serif'],
                label: ['Inter', 'sans-serif'],
                inter: ['Inter', 'sans-serif'],
            },
        },
    },
    plugins: [],
};

export default config;
