USE ObservatorioDW;
GO


--Eliminar los datos de las tablas de dimensiones y hechos para pruebas
DELETE FROM dbo.FACT_EVENTO;

-- Luego las dimensiones
DELETE FROM dbo.DIM_TIEMPO;
DELETE FROM dbo.DIM_LUGAR;
DELETE FROM dbo.DIM_PERSONA;
DELETE FROM dbo.DIM_METODO;
DELETE FROM dbo.DIM_ATENCION;
DELETE FROM dbo.DIM_CONTEXTO;

-- Limpiar en orden correcto
DELETE FROM dbo.FACT_EVENTO;
DBCC CHECKIDENT ('dbo.FACT_EVENTO', RESEED, 0);

DELETE FROM dbo.DIM_PERSONA;
DBCC CHECKIDENT ('dbo.DIM_PERSONA', RESEED, 0);

DELETE FROM dbo.DIM_TIEMPO;
DBCC CHECKIDENT ('dbo.DIM_TIEMPO', RESEED, 0);

DELETE FROM dbo.DIM_LUGAR;
DBCC CHECKIDENT ('dbo.DIM_LUGAR', RESEED, 0);

DELETE FROM dbo.DIM_METODO;
DBCC CHECKIDENT ('dbo.DIM_METODO', RESEED, 0);

DELETE FROM dbo.DIM_ATENCION;
DBCC CHECKIDENT ('dbo.DIM_ATENCION', RESEED, 0);

DELETE FROM dbo.DIM_CONTEXTO;
DBCC CHECKIDENT ('dbo.DIM_CONTEXTO', RESEED, 0);
