USE ObservatorioDW;
DELETE FROM FACT_EVENTO;
DELETE FROM DIM_ATENCION;
DELETE FROM DIM_CONTEXTO;
DELETE FROM DIM_LUGAR;
DELETE FROM DIM_METODO;
DELETE FROM DIM_TIEMPO;
DELETE FROM DIM_PERSONA;
DBCC CHECKIDENT ('DIM_PERSONA',  RESEED, 0);
DBCC CHECKIDENT ('DIM_TIEMPO',   RESEED, 0);
DBCC CHECKIDENT ('DIM_LUGAR',    RESEED, 0);
DBCC CHECKIDENT ('DIM_METODO',   RESEED, 0);
DBCC CHECKIDENT ('DIM_ATENCION', RESEED, 0);
DBCC CHECKIDENT ('DIM_CONTEXTO', RESEED, 0);


SELECT COUNT(*) FROM DIM_PERSONA;